<a href="https://colab.research.google.com/github/Mayank0195/IMDB_Web_Scraping/blob/main/Action_movie_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import requests 
from bs4 import BeautifulSoup
from time import sleep
from random import randint

In [2]:
#Declaring the headers
header = {"Accept-Language" : "en-US, en; q = 0.5"}

In [3]:
movie_name = []
year = []
time=[]
rating=[]
genres =[]
description = []
director = []
casts = []

In [4]:
#creating an array of values and passing it in the url for dynamic webpages
pages = np.arange(1,25000,50)

#the whole core of the script
for page in pages:
    page = requests.get("https://www.imdb.com/search/title/?title_type=feature&genres=action&sort=alpha,asc&start="+str(page)+"&explore=genres&ref_=adv_nxt")
    soup = BeautifulSoup(page.text, 'html.parser')
    movie_data = soup.findAll('div', attrs = {'class': 'lister-item mode-advanced'})
    sleep(randint(2,8))
    for store in movie_data:
            name = store.find('h3', class_= 'lister-item-header').find('a').text
            movie_name.append(name)

            year_of_release = store.h3.find('span', class_ = "lister-item-year text-muted unbold").text[1:5]
            year.append(year_of_release)

            
            try: 
              runtime = store.p.find('span', class_ = 'runtime').text[0:7]
              time.append(runtime)
            except:
              time.append(None)

            rate = store.find('div', class_ = "inline-block ratings-imdb-rating")
            try:
              ratings = (rate.find('strong').text)
              rating.append(ratings)
            except:
              rating.append(None)

            genre = store.p.find('span', class_ = 'genre').text.replace('\n', '')
            genres.append(genre)

            describe = store.find_all('p', class_ = 'text-muted')
            description_ = describe[1].text.replace('\n', '') if len(describe) >1 else '*****'
            description.append(description_)
            
            try:
              direct = store.select_one("p:nth-of-type(3)").find('a').text[:]
              director.append(direct)
            except:
              director.append(None)

            try:
              cast = store.select_one("p:nth-of-type(3)").select_one("a:nth-of-type(2)").text[:],store.select_one("p:nth-of-type(3)").select_one("a:nth-of-type(3)").text[:]
              casts.append(cast)
            except:
              casts.append(None)

In [5]:
a = { "Movie Name": movie_name, "Year of Release" : year, "Watch Time": time,"Movie Rating": rating, "Genres": genres, "Description":description, "Director":director, "Cast":casts}

In [6]:
df = pd.DataFrame.from_dict(a, orient='index')
df = df.transpose()
df.head()

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
0,#66,2015,116 min,5.7,Action,"66 tells the story of an assassin-for-hire, wh...",Asun Mawardi,"(Ari Riski Ananda, Erwin Bagindo)"
1,#FightClub Blood Out,,None,None,"Action, Drama",Add a Plot,Romane Simon,"(Luis Moncada, Blac Chyna)"
2,#Santa4Real,,None,None,"Action, Adventure, Comedy",3 best friends go on an adventure to prove tha...,Ben Deka,None
3,#Alive,2020,98 min,6.3,"Action, Drama, Horror",The rapid spread of an unknown infection has l...,Il Cho,"(Yoo Ah-in, Park Shin-Hye)"
4,#Selfieparty,2016,90 min,5.2,"Action, Comedy, Thriller","Four friends who are all students, wake up at ...",Lyubomyr Levytsky,"(Sergei Zorenko, Boris Savenko)"

In [7]:
df.to_csv('Test.csv')

In [8]:
df.tail()

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
24993,.9999 (Four Nines Fine),,None,None,Action,Five billion dollars in gold is missing from a...,None,None
24994,.hack//G.U. Trilogy,2007,93 min,5.4,"Animation, Action, Adventure",After one of his friends falls into a coma pla...,Hiroshi Matsuyama,"(Takahiro Sakurai, Ayako Kawasumi)"
24995,Oh! Those Most Secret Agents,1964,83 min,5.6,"Action, Comedy",Franco and Ciccio are two simple-minded Italia...,Lucio Fulci,"(Franco Franchi, Ciccio Ingrassia)"
24996,006 kaçis,2014,None,4.0,"Action, Comedy",Add a Plot,Ferhat Alpözen,"(Ismail Nadir Bilgili, Furat Emir)"
24997,009 Re: Cyborg,2012,103 min,5.8,"Animation, Action, Sci-Fi","All over the world, ordinary people are commit...",Kenji Kamiyama,"(Chiwa Saitô, Daisuke Ono)"

In [9]:
df = df.dropna()
df

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
0,#66,2015,116 min,5.7,Action,"66 tells the story of an assassin-for-hire, wh...",Asun Mawardi,"(Ari Riski Ananda, Erwin Bagindo)"
3,#Alive,2020,98 min,6.3,"Action, Drama, Horror",The rapid spread of an unknown infection has l...,Il Cho,"(Yoo Ah-in, Park Shin-Hye)"
4,#Selfieparty,2016,90 min,5.2,"Action, Comedy, Thriller","Four friends who are all students, wake up at ...",Lyubomyr Levytsky,"(Sergei Zorenko, Boris Savenko)"
6,#Victoria,2018,119 min,4.3,"Action, Drama, Thriller",Victoria moves from out of town into the poor ...,Mark K. Buddington,"(Jason Barkley, Mark K. Buddington)"
9,$50K and a Call Girl: A Love Story,2014,90 min,6.8,"Action, Adventure, Comedy",When Ross is diagnosed with terminal brain can...,Seth Grossman,"(Ross Patterson, Jessie Wiseman)"
...,...,...,...,...,...,...,...,...
24991,.357,2013,97 min,5.0,"Action, Drama","On her wedding night, Jade wakes up holding th...",Brian Skiba,"(Laurie Love, Fred Williamson)"
24992,.357 Magnum,1977,71 min,4.4,"Action, Drama",Agent Jonathan Hightower's weapon of chose is ...,Nick Millard,"(Gary Boyd, Silvi Walter)"
24994,.hack//G.U. Trilogy,2007,93 min,5.4,"Animation, Action, Adventure",After one of his friends falls into a coma pla...,Hiroshi Matsuyama,"(Takahiro Sakurai, Ayako Kawasumi)"
24995,Oh! Those Most Secret Agents,1964,83 min,5.6,"Action, Comedy",Franco and Ciccio are two simple-minded Italia...,Lucio Fulci,"(Franco Franchi, Ciccio Ingrassia)"
24997,009 Re: Cyborg,2012,103 min,5.8,"Animation, Action, Sci-Fi","All over the world, ordinary people are commit...",Kenji Kamiyama,"(Chiwa Saitô, Daisuke Ono)"

In [10]:
df.sort_values("Movie Name", inplace=False)
df

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
0,#66,2015,116 min,5.7,Action,"66 tells the story of an assassin-for-hire, wh...",Asun Mawardi,"(Ari Riski Ananda, Erwin Bagindo)"
3,#Alive,2020,98 min,6.3,"Action, Drama, Horror",The rapid spread of an unknown infection has l...,Il Cho,"(Yoo Ah-in, Park Shin-Hye)"
4,#Selfieparty,2016,90 min,5.2,"Action, Comedy, Thriller","Four friends who are all students, wake up at ...",Lyubomyr Levytsky,"(Sergei Zorenko, Boris Savenko)"
6,#Victoria,2018,119 min,4.3,"Action, Drama, Thriller",Victoria moves from out of town into the poor ...,Mark K. Buddington,"(Jason Barkley, Mark K. Buddington)"
9,$50K and a Call Girl: A Love Story,2014,90 min,6.8,"Action, Adventure, Comedy",When Ross is diagnosed with terminal brain can...,Seth Grossman,"(Ross Patterson, Jessie Wiseman)"
...,...,...,...,...,...,...,...,...
24991,.357,2013,97 min,5.0,"Action, Drama","On her wedding night, Jade wakes up holding th...",Brian Skiba,"(Laurie Love, Fred Williamson)"
24992,.357 Magnum,1977,71 min,4.4,"Action, Drama",Agent Jonathan Hightower's weapon of chose is ...,Nick Millard,"(Gary Boyd, Silvi Walter)"
24994,.hack//G.U. Trilogy,2007,93 min,5.4,"Animation, Action, Adventure",After one of his friends falls into a coma pla...,Hiroshi Matsuyama,"(Takahiro Sakurai, Ayako Kawasumi)"
24995,Oh! Those Most Secret Agents,1964,83 min,5.6,"Action, Comedy",Franco and Ciccio are two simple-minded Italia...,Lucio Fulci,"(Franco Franchi, Ciccio Ingrassia)"
24997,009 Re: Cyborg,2012,103 min,5.8,"Animation, Action, Sci-Fi","All over the world, ordinary people are commit...",Kenji Kamiyama,"(Chiwa Saitô, Daisuke Ono)"

In [11]:
df = df.drop_duplicates(subset='Movie Name')
df

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
0,#66,2015,116 min,5.7,Action,"66 tells the story of an assassin-for-hire, wh...",Asun Mawardi,"(Ari Riski Ananda, Erwin Bagindo)"
3,#Alive,2020,98 min,6.3,"Action, Drama, Horror",The rapid spread of an unknown infection has l...,Il Cho,"(Yoo Ah-in, Park Shin-Hye)"
4,#Selfieparty,2016,90 min,5.2,"Action, Comedy, Thriller","Four friends who are all students, wake up at ...",Lyubomyr Levytsky,"(Sergei Zorenko, Boris Savenko)"
6,#Victoria,2018,119 min,4.3,"Action, Drama, Thriller",Victoria moves from out of town into the poor ...,Mark K. Buddington,"(Jason Barkley, Mark K. Buddington)"
9,$50K and a Call Girl: A Love Story,2014,90 min,6.8,"Action, Adventure, Comedy",When Ross is diagnosed with terminal brain can...,Seth Grossman,"(Ross Patterson, Jessie Wiseman)"
...,...,...,...,...,...,...,...,...
9990,Danger Close,2019,118 min,6.8,"Action, Drama, War","In August 1966, in a Vietnamese rubber plantat...",Kriv Stenders,"(Travis Fimmel, Toby Blome)"
9991,Danger Diva,2020,105 min,8.4,"Action, Sci-Fi, Thriller",DANGER DIVA is a cyberpunk musical/thriller ab...,Robert McGinley,"(Molly Sides, Mike Dooly)"
9993,Danger Island,1931,220 min,5.8,"Action, Adventure, Romance",The daughter of a man who has discovered radiu...,Ray Taylor,"(Kenneth Harlan, Lucile Browne)"
9994,Danger One,2018,101 min,6.0,"Action, Comedy, Crime",While transporting a dying man to the hospital...,Tom Oesch,"(Tom Everett Scott, James Jurdi)"
9996,Danger Patrol,1937,59 min,5.5,"Action, Drama, Romance",A romance drama involving people who transport...,Lew Landers,"(Sally Eilers, John Beal)"

In [12]:
df = df.reset_index(drop=True)
df

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
0,#66,2015,116 min,5.7,Action,"66 tells the story of an assassin-for-hire, wh...",Asun Mawardi,"(Ari Riski Ananda, Erwin Bagindo)"
1,#Alive,2020,98 min,6.3,"Action, Drama, Horror",The rapid spread of an unknown infection has l...,Il Cho,"(Yoo Ah-in, Park Shin-Hye)"
2,#Selfieparty,2016,90 min,5.2,"Action, Comedy, Thriller","Four friends who are all students, wake up at ...",Lyubomyr Levytsky,"(Sergei Zorenko, Boris Savenko)"
3,#Victoria,2018,119 min,4.3,"Action, Drama, Thriller",Victoria moves from out of town into the poor ...,Mark K. Buddington,"(Jason Barkley, Mark K. Buddington)"
4,$50K and a Call Girl: A Love Story,2014,90 min,6.8,"Action, Adventure, Comedy",When Ross is diagnosed with terminal brain can...,Seth Grossman,"(Ross Patterson, Jessie Wiseman)"
...,...,...,...,...,...,...,...,...
4674,Danger Close,2019,118 min,6.8,"Action, Drama, War","In August 1966, in a Vietnamese rubber plantat...",Kriv Stenders,"(Travis Fimmel, Toby Blome)"
4675,Danger Diva,2020,105 min,8.4,"Action, Sci-Fi, Thriller",DANGER DIVA is a cyberpunk musical/thriller ab...,Robert McGinley,"(Molly Sides, Mike Dooly)"
4676,Danger Island,1931,220 min,5.8,"Action, Adventure, Romance",The daughter of a man who has discovered radiu...,Ray Taylor,"(Kenneth Harlan, Lucile Browne)"
4677,Danger One,2018,101 min,6.0,"Action, Comedy, Crime",While transporting a dying man to the hospital...,Tom Oesch,"(Tom Everett Scott, James Jurdi)"
4678,Danger Patrol,1937,59 min,5.5,"Action, Drama, Romance",A romance drama involving people who transport...,Lew Landers,"(Sally Eilers, John Beal)"

In [13]:
df.to_csv('movies.csv')

In [14]:
#creating an array of values and passing it in the url for dynamic webpages
pages = np.arange(25000,51390,50)

#the whole core of the script
for page in pages:
    page = requests.get("https://www.imdb.com/search/title/?title_type=feature&genres=action&sort=alpha,asc&start="+str(page)+"&explore=genres&ref_=adv_nxt")
    soup = BeautifulSoup(page.text, 'html.parser')
    movie_data = soup.findAll('div', attrs = {'class': 'lister-item mode-advanced'})
    sleep(randint(2,8))
    for store in movie_data:
            name = store.find('h3', class_= 'lister-item-header').find('a').text
            movie_name.append(name)

            year_of_release = store.h3.find('span', class_ = "lister-item-year text-muted unbold").text[1:5]
            year.append(year_of_release)

            
            try: 
              runtime = store.p.find('span', class_ = 'runtime').text[0:7]
              time.append(runtime)
            except:
              time.append(None)

            rate = store.find('div', class_ = "inline-block ratings-imdb-rating")
            try:
              ratings = (rate.find('strong').text)
              rating.append(ratings)
            except:
              rating.append(None)

            genre = store.p.find('span', class_ = 'genre').text.replace('\n', '')
            genres.append(genre)

            describe = store.find_all('p', class_ = 'text-muted')
            description_ = describe[1].text.replace('\n', '') if len(describe) >1 else '*****'
            description.append(description_)
            
            try:
              direct = store.select_one("p:nth-of-type(3)").find('a').text[:]
              director.append(direct)
            except:
              director.append(None)

            try:
              cast = store.select_one("p:nth-of-type(3)").select_one("a:nth-of-type(2)").text[:],store.select_one("p:nth-of-type(3)").select_one("a:nth-of-type(3)").text[:]
              casts.append(cast)
            except:
              casts.append(None)

In [15]:
b = { "Movie Name": movie_name, "Year of Release" : year, "Watch Time": time,"Movie Rating": rating, "Genres": genres, "Description":description, "Director":director, "Cast":casts}

In [16]:
df1 = pd.DataFrame.from_dict(b, orient='index')
df1 = df1.transpose()
df1.head()

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
0,#66,2015,116 min,5.7,Action,"66 tells the story of an assassin-for-hire, wh...",Asun Mawardi,"(Ari Riski Ananda, Erwin Bagindo)"
1,#FightClub Blood Out,,None,None,"Action, Drama",Add a Plot,Romane Simon,"(Luis Moncada, Blac Chyna)"
2,#Santa4Real,,None,None,"Action, Adventure, Comedy",3 best friends go on an adventure to prove tha...,Ben Deka,None
3,#Alive,2020,98 min,6.3,"Action, Drama, Horror",The rapid spread of an unknown infection has l...,Il Cho,"(Yoo Ah-in, Park Shin-Hye)"
4,#Selfieparty,2016,90 min,5.2,"Action, Comedy, Thriller","Four friends who are all students, wake up at ...",Lyubomyr Levytsky,"(Sergei Zorenko, Boris Savenko)"

In [17]:
df = df.append(df1,ignore_index=True)

In [18]:
df

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
0,#66,2015,116 min,5.7,Action,"66 tells the story of an assassin-for-hire, wh...",Asun Mawardi,"(Ari Riski Ananda, Erwin Bagindo)"
1,#Alive,2020,98 min,6.3,"Action, Drama, Horror",The rapid spread of an unknown infection has l...,Il Cho,"(Yoo Ah-in, Park Shin-Hye)"
2,#Selfieparty,2016,90 min,5.2,"Action, Comedy, Thriller","Four friends who are all students, wake up at ...",Lyubomyr Levytsky,"(Sergei Zorenko, Boris Savenko)"
3,#Victoria,2018,119 min,4.3,"Action, Drama, Thriller",Victoria moves from out of town into the poor ...,Mark K. Buddington,"(Jason Barkley, Mark K. Buddington)"
4,$50K and a Call Girl: A Love Story,2014,90 min,6.8,"Action, Adventure, Comedy",When Ross is diagnosed with terminal brain can...,Seth Grossman,"(Ross Patterson, Jessie Wiseman)"
...,...,...,...,...,...,...,...,...
56072,.9999 (Four Nines Fine),,None,None,Action,Five billion dollars in gold is missing from a...,None,None
56073,.hack//G.U. Trilogy,2007,93 min,5.4,"Animation, Action, Adventure",After one of his friends falls into a coma pla...,Hiroshi Matsuyama,"(Takahiro Sakurai, Ayako Kawasumi)"
56074,Oh! Those Most Secret Agents,1964,83 min,5.6,"Action, Comedy",Franco and Ciccio are two simple-minded Italia...,Lucio Fulci,"(Franco Franchi, Ciccio Ingrassia)"
56075,006 kaçis,2014,None,4.0,"Action, Comedy",Add a Plot,Ferhat Alpözen,"(Ismail Nadir Bilgili, Furat Emir)"
56076,009 Re: Cyborg,2012,103 min,5.8,"Animation, Action, Sci-Fi","All over the world, ordinary people are commit...",Kenji Kamiyama,"(Chiwa Saitô, Daisuke Ono)"

In [19]:
df.sort_values("Movie Name", inplace=False)

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
0,#66,2015,116 min,5.7,Action,"66 tells the story of an assassin-for-hire, wh...",Asun Mawardi,"(Ari Riski Ananda, Erwin Bagindo)"
39677,#66,2015,116 min,5.7,Action,"66 tells the story of an assassin-for-hire, wh...",Asun Mawardi,"(Ari Riski Ananda, Erwin Bagindo)"
39727,#66,2015,116 min,5.7,Action,"66 tells the story of an assassin-for-hire, wh...",Asun Mawardi,"(Ari Riski Ananda, Erwin Bagindo)"
39777,#66,2015,116 min,5.7,Action,"66 tells the story of an assassin-for-hire, wh...",Asun Mawardi,"(Ari Riski Ananda, Erwin Bagindo)"
39827,#66,2015,116 min,5.7,Action,"66 tells the story of an assassin-for-hire, wh...",Asun Mawardi,"(Ari Riski Ananda, Erwin Bagindo)"
...,...,...,...,...,...,...,...,...
18406,Z Storm,2014,92 min,5.3,"Action, Crime",This is a story about the biggest financial fr...,David Lam,"(Louis Koo, Ka-Tung Lam)"
39806,Z Storm,2014,92 min,5.3,"Action, Crime",This is a story about the biggest financial fr...,David Lam,"(Louis Koo, Ka-Tung Lam)"
16806,Z Storm,2014,92 min,5.3,"Action, Crime",This is a story about the biggest financial fr...,David Lam,"(Louis Koo, Ka-Tung Lam)"
54656,Z Storm,2014,92 min,5.3,"Action, Crime",This is a story about the biggest financial fr...,David Lam,"(Louis Koo, Ka-Tung Lam)"
9226,Zona Surena,2009,80 min,None,"Action, Crime, Drama","A small town in Texas, a group of gang members...",Luis Antonio Rodriguez,"(Marcelino 'Dibujo' Torres, Ramiro Cavazos)"

In [20]:
df = df.dropna()

In [21]:
df

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
0,#66,2015,116 min,5.7,Action,"66 tells the story of an assassin-for-hire, wh...",Asun Mawardi,"(Ari Riski Ananda, Erwin Bagindo)"
1,#Alive,2020,98 min,6.3,"Action, Drama, Horror",The rapid spread of an unknown infection has l...,Il Cho,"(Yoo Ah-in, Park Shin-Hye)"
2,#Selfieparty,2016,90 min,5.2,"Action, Comedy, Thriller","Four friends who are all students, wake up at ...",Lyubomyr Levytsky,"(Sergei Zorenko, Boris Savenko)"
3,#Victoria,2018,119 min,4.3,"Action, Drama, Thriller",Victoria moves from out of town into the poor ...,Mark K. Buddington,"(Jason Barkley, Mark K. Buddington)"
4,$50K and a Call Girl: A Love Story,2014,90 min,6.8,"Action, Adventure, Comedy",When Ross is diagnosed with terminal brain can...,Seth Grossman,"(Ross Patterson, Jessie Wiseman)"
...,...,...,...,...,...,...,...,...
56070,.357,2013,97 min,5.0,"Action, Drama","On her wedding night, Jade wakes up holding th...",Brian Skiba,"(Laurie Love, Fred Williamson)"
56071,.357 Magnum,1977,71 min,4.4,"Action, Drama",Agent Jonathan Hightower's weapon of chose is ...,Nick Millard,"(Gary Boyd, Silvi Walter)"
56073,.hack//G.U. Trilogy,2007,93 min,5.4,"Animation, Action, Adventure",After one of his friends falls into a coma pla...,Hiroshi Matsuyama,"(Takahiro Sakurai, Ayako Kawasumi)"
56074,Oh! Those Most Secret Agents,1964,83 min,5.6,"Action, Comedy",Franco and Ciccio are two simple-minded Italia...,Lucio Fulci,"(Franco Franchi, Ciccio Ingrassia)"
56076,009 Re: Cyborg,2012,103 min,5.8,"Animation, Action, Sci-Fi","All over the world, ordinary people are commit...",Kenji Kamiyama,"(Chiwa Saitô, Daisuke Ono)"

In [22]:
df = df.reset_index(drop=True)
df

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
0,#66,2015,116 min,5.7,Action,"66 tells the story of an assassin-for-hire, wh...",Asun Mawardi,"(Ari Riski Ananda, Erwin Bagindo)"
1,#Alive,2020,98 min,6.3,"Action, Drama, Horror",The rapid spread of an unknown infection has l...,Il Cho,"(Yoo Ah-in, Park Shin-Hye)"
2,#Selfieparty,2016,90 min,5.2,"Action, Comedy, Thriller","Four friends who are all students, wake up at ...",Lyubomyr Levytsky,"(Sergei Zorenko, Boris Savenko)"
3,#Victoria,2018,119 min,4.3,"Action, Drama, Thriller",Victoria moves from out of town into the poor ...,Mark K. Buddington,"(Jason Barkley, Mark K. Buddington)"
4,$50K and a Call Girl: A Love Story,2014,90 min,6.8,"Action, Adventure, Comedy",When Ross is diagnosed with terminal brain can...,Seth Grossman,"(Ross Patterson, Jessie Wiseman)"
...,...,...,...,...,...,...,...,...
38532,.357,2013,97 min,5.0,"Action, Drama","On her wedding night, Jade wakes up holding th...",Brian Skiba,"(Laurie Love, Fred Williamson)"
38533,.357 Magnum,1977,71 min,4.4,"Action, Drama",Agent Jonathan Hightower's weapon of chose is ...,Nick Millard,"(Gary Boyd, Silvi Walter)"
38534,.hack//G.U. Trilogy,2007,93 min,5.4,"Animation, Action, Adventure",After one of his friends falls into a coma pla...,Hiroshi Matsuyama,"(Takahiro Sakurai, Ayako Kawasumi)"
38535,Oh! Those Most Secret Agents,1964,83 min,5.6,"Action, Comedy",Franco and Ciccio are two simple-minded Italia...,Lucio Fulci,"(Franco Franchi, Ciccio Ingrassia)"
38536,009 Re: Cyborg,2012,103 min,5.8,"Animation, Action, Sci-Fi","All over the world, ordinary people are commit...",Kenji Kamiyama,"(Chiwa Saitô, Daisuke Ono)"

In [23]:
df = df.drop_duplicates(subset='Movie Name')

In [24]:
df

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
0,#66,2015,116 min,5.7,Action,"66 tells the story of an assassin-for-hire, wh...",Asun Mawardi,"(Ari Riski Ananda, Erwin Bagindo)"
1,#Alive,2020,98 min,6.3,"Action, Drama, Horror",The rapid spread of an unknown infection has l...,Il Cho,"(Yoo Ah-in, Park Shin-Hye)"
2,#Selfieparty,2016,90 min,5.2,"Action, Comedy, Thriller","Four friends who are all students, wake up at ...",Lyubomyr Levytsky,"(Sergei Zorenko, Boris Savenko)"
3,#Victoria,2018,119 min,4.3,"Action, Drama, Thriller",Victoria moves from out of town into the poor ...,Mark K. Buddington,"(Jason Barkley, Mark K. Buddington)"
4,$50K and a Call Girl: A Love Story,2014,90 min,6.8,"Action, Adventure, Comedy",When Ross is diagnosed with terminal brain can...,Seth Grossman,"(Ross Patterson, Jessie Wiseman)"
...,...,...,...,...,...,...,...,...
4674,Danger Close,2019,118 min,6.8,"Action, Drama, War","In August 1966, in a Vietnamese rubber plantat...",Kriv Stenders,"(Travis Fimmel, Toby Blome)"
4675,Danger Diva,2020,105 min,8.4,"Action, Sci-Fi, Thriller",DANGER DIVA is a cyberpunk musical/thriller ab...,Robert McGinley,"(Molly Sides, Mike Dooly)"
4676,Danger Island,1931,220 min,5.8,"Action, Adventure, Romance",The daughter of a man who has discovered radiu...,Ray Taylor,"(Kenneth Harlan, Lucile Browne)"
4677,Danger One,2018,101 min,6.0,"Action, Comedy, Crime",While transporting a dying man to the hospital...,Tom Oesch,"(Tom Everett Scott, James Jurdi)"
4678,Danger Patrol,1937,59 min,5.5,"Action, Drama, Romance",A romance drama involving people who transport...,Lew Landers,"(Sally Eilers, John Beal)"

In [25]:
df = df.reset_index(drop=True)
df

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
0,#66,2015,116 min,5.7,Action,"66 tells the story of an assassin-for-hire, wh...",Asun Mawardi,"(Ari Riski Ananda, Erwin Bagindo)"
1,#Alive,2020,98 min,6.3,"Action, Drama, Horror",The rapid spread of an unknown infection has l...,Il Cho,"(Yoo Ah-in, Park Shin-Hye)"
2,#Selfieparty,2016,90 min,5.2,"Action, Comedy, Thriller","Four friends who are all students, wake up at ...",Lyubomyr Levytsky,"(Sergei Zorenko, Boris Savenko)"
3,#Victoria,2018,119 min,4.3,"Action, Drama, Thriller",Victoria moves from out of town into the poor ...,Mark K. Buddington,"(Jason Barkley, Mark K. Buddington)"
4,$50K and a Call Girl: A Love Story,2014,90 min,6.8,"Action, Adventure, Comedy",When Ross is diagnosed with terminal brain can...,Seth Grossman,"(Ross Patterson, Jessie Wiseman)"
...,...,...,...,...,...,...,...,...
4674,Danger Close,2019,118 min,6.8,"Action, Drama, War","In August 1966, in a Vietnamese rubber plantat...",Kriv Stenders,"(Travis Fimmel, Toby Blome)"
4675,Danger Diva,2020,105 min,8.4,"Action, Sci-Fi, Thriller",DANGER DIVA is a cyberpunk musical/thriller ab...,Robert McGinley,"(Molly Sides, Mike Dooly)"
4676,Danger Island,1931,220 min,5.8,"Action, Adventure, Romance",The daughter of a man who has discovered radiu...,Ray Taylor,"(Kenneth Harlan, Lucile Browne)"
4677,Danger One,2018,101 min,6.0,"Action, Comedy, Crime",While transporting a dying man to the hospital...,Tom Oesch,"(Tom Everett Scott, James Jurdi)"
4678,Danger Patrol,1937,59 min,5.5,"Action, Drama, Romance",A romance drama involving people who transport...,Lew Landers,"(Sally Eilers, John Beal)"

In [27]:
df.to_csv('movies.csv')

In [29]:
df[56:]

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
56,100 kilos de plomo,2002,90 min,3.2,Action,Add a Plot,Raymundo Calixto,"(Jorge Aldama, Eric del Castillo)"
57,"100% lucha, el amo de los clones",2009,80 min,5.2,"Action, Adventure, Sci-Fi",The movie of the popular Argentinian wrestling...,Pablo Parés,"(Paulo Soria, Roberto Carnaghi)"
58,"100% lucha, la película",2008,83 min,4.6,"Action, Adventure, Comedy","Koshe Plostenko (Carlos Kaspar), a mob man, is...",Juan Iribas,"(Chechu Bonelli, Eduardo Husni)"
59,10000 Hours,2013,107 min,7.2,"Action, Drama, Thriller",A senator is forced to go on the run after kil...,Joyce Bernal,"(Robin Padilla, Michael De Mesa)"
60,100Volta,2009,120 min,3.7,"Action, Adventure, Comedy",Add a Plot,Daniel Souza,"(Daniel Souza, Rafael Sousa)"
...,...,...,...,...,...,...,...,...
4674,Danger Close,2019,118 min,6.8,"Action, Drama, War","In August 1966, in a Vietnamese rubber plantat...",Kriv Stenders,"(Travis Fimmel, Toby Blome)"
4675,Danger Diva,2020,105 min,8.4,"Action, Sci-Fi, Thriller",DANGER DIVA is a cyberpunk musical/thriller ab...,Robert McGinley,"(Molly Sides, Mike Dooly)"
4676,Danger Island,1931,220 min,5.8,"Action, Adventure, Romance",The daughter of a man who has discovered radiu...,Ray Taylor,"(Kenneth Harlan, Lucile Browne)"
4677,Danger One,2018,101 min,6.0,"Action, Comedy, Crime",While transporting a dying man to the hospital...,Tom Oesch,"(Tom Everett Scott, James Jurdi)"
4678,Danger Patrol,1937,59 min,5.5,"Action, Drama, Romance",A romance drama involving people who transport...,Lew Landers,"(Sally Eilers, John Beal)"