<a href="https://colab.research.google.com/github/Mayank0195/IMDB_Web_Scraping/blob/main/Sci_Fi_movie_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import requests 
from bs4 import BeautifulSoup
from time import sleep
from random import randint

In [2]:
#Declaring the headers
header = {"Accept-Language" : "en-US, en; q = 0.5"}

In [3]:
movie_name = []
year = []
time=[]
rating=[]
genres =[]
description = []
director = []
casts = []

In [4]:
#creating an array of values and passing it in the url for dynamic webpages
pages = list(np.arange(1,16103,50))
print(pages)

#the whole core of the script
for page in pages:
    pag = requests.get("https://www.imdb.com/search/title/?title_type=feature&genres=Sci-Fi&start={}&explore=genres&ref_=adv_nxt".format(page))
    soup = BeautifulSoup(pag.text, 'html.parser')
    movie_data = soup.findAll('div', attrs = {'class': 'lister-item mode-advanced'})
    sleep(randint(2,8))
    for store in movie_data:
            name = store.find('h3', class_= 'lister-item-header').find('a').text
            movie_name.append(name)

            release = store.find('h3', class_= 'lister-item-header')
            try:
              year_of_release = store.find('span', class_ = "lister-item-year text-muted unbold").text[1:5]
              year.append(year_of_release)
            except:
              year.append(None)

            try: 
              runtime = store.p.find('span', class_ = 'runtime').text[0:7]
              time.append(runtime)
            except:
              time.append(None)

            rate = store.find('div', class_ = "inline-block ratings-imdb-rating")
            try:
              ratings = (rate.find('strong').text)
              rating.append(ratings)
            except:
              rating.append(None)

            genre = store.p.find('span', class_ = 'genre').text.replace('\n', '')
            genres.append(genre)

            describe = store.find_all('p', class_ = 'text-muted')
            description_ = describe[1].text.replace('\n', '') if len(describe) >1 else '*****'
            description.append(description_)
            
            try:
              direct = store.select_one("p:nth-of-type(3)").find('a').text[:]
              director.append(direct)
            except:
              director.append(None)

            try:
              cast = store.select_one("p:nth-of-type(3)").select_one("a:nth-of-type(2)").text[:],store.select_one("p:nth-of-type(3)").select_one("a:nth-of-type(3)").text[:]
              casts.append(cast)
            except:
              casts.append(None)

[1, 51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601, 651, 701, 751, 801, 851, 901, 951, 1001, 1051, 1101, 1151, 1201, 1251, 1301, 1351, 1401, 1451, 1501, 1551, 1601, 1651, 1701, 1751, 1801, 1851, 1901, 1951, 2001, 2051, 2101, 2151, 2201, 2251, 2301, 2351, 2401, 2451, 2501, 2551, 2601, 2651, 2701, 2751, 2801, 2851, 2901, 2951, 3001, 3051, 3101, 3151, 3201, 3251, 3301, 3351, 3401, 3451, 3501, 3551, 3601, 3651, 3701, 3751, 3801, 3851, 3901, 3951, 4001, 4051, 4101, 4151, 4201, 4251, 4301, 4351, 4401, 4451, 4501, 4551, 4601, 4651, 4701, 4751, 4801, 4851, 4901, 4951, 5001, 5051, 5101, 5151, 5201, 5251, 5301, 5351, 5401, 5451, 5501, 5551, 5601, 5651, 5701, 5751, 5801, 5851, 5901, 5951, 6001, 6051, 6101, 6151, 6201, 6251, 6301, 6351, 6401, 6451, 6501, 6551, 6601, 6651, 6701, 6751, 6801, 6851, 6901, 6951, 7001, 7051, 7101, 7151, 7201, 7251, 7301, 7351, 7401, 7451, 7501, 7551, 7601, 7651, 7701, 7751, 7801, 7851, 7901, 7951, 8001, 8051, 8101, 8151, 8201, 8251, 8301, 8351, 8401, 8451, 8501, 8551, 8601, 8651, 8701, 8751, 8801, 8851, 8901, 8951, 9001, 9051, 9101, 9151, 9201, 9251, 9301, 9351, 9401, 9451, 9501, 9551, 9601, 9651, 9701, 9751, 9801, 9851, 9901, 9951, 10001, 10051, 10101, 10151, 10201, 10251, 10301, 10351, 10401, 10451, 10501, 10551, 10601, 10651, 10701, 10751, 10801, 10851, 10901, 10951, 11001, 11051, 11101, 11151, 11201, 11251, 11301, 11351, 11401, 11451, 11501, 11551, 11601, 11651, 11701, 11751, 11801, 11851, 11901, 11951, 12001, 12051, 12101, 12151, 12201, 12251, 12301, 12351, 12401, 12451, 12501, 12551, 12601, 12651, 12701, 12751, 12801, 12851, 12901, 12951, 13001, 13051, 13101, 13151, 13201, 13251, 13301, 13351, 13401, 13451, 13501, 13551, 13601, 13651, 13701, 13751, 13801, 13851, 13901, 13951, 14001, 14051, 14101, 14151, 14201, 14251, 14301, 14351, 14401, 14451, 14501, 14551, 14601, 14651, 14701, 14751, 14801, 14851, 14901, 14951, 15001, 15051, 15101, 15151, 15201, 15251, 15301, 15351, 15401, 15451, 15501, 15551, 15601, 15651, 15701, 15751, 15801, 15851, 15901, 15951, 16001, 16051, 16101]

In [5]:
a = { "Movie Name": movie_name, "Year of Release" : year, "Watch Time": time,"Movie Rating": rating, "Genres": genres, "Description":description, "Director":director, "Cast":casts}

In [6]:
df = pd.DataFrame.from_dict(a, orient='index')
df = df.transpose()
df.head()

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
0,Thor: Love and Thunder,2022,118 min,6.4,"Action, Adventure, Comedy","Thor enlists the help of Valkyrie, Korg and ex...",Taika Waititi,"(Chris Hemsworth, Natalie Portman)"
1,Nope,2022,130 min,7.0,"Horror, Mystery, Sci-Fi",The residents of a lonely gulch in inland Cali...,Jordan Peele,"(Daniel Kaluuya, Keke Palmer)"
2,Avatar: The Way of Water,2022,None,None,"Action, Adventure, Fantasy",Jake Sully lives with his newfound family form...,James Cameron,"(Zoe Saldana, Kate Winslet)"
3,Everything Everywhere All at Once,2022,139 min,8.1,"Action, Adventure, Comedy",An aging Chinese immigrant is swept up in an i...,Dan Kwan,"(Daniel Scheinert, Michelle Yeoh)"
4,The Munsters,2022,109 min,None,"Comedy, Family, Fantasy","Reboot of ""The Munsters"", that followed a fami...",Rob Zombie,"(Cassandra Peterson, Sheri Moon Zombie)"

In [7]:
df.shape

(16149, 8)

In [8]:
df['Movie Name'].value_counts()

Prey                    126
Crimes of the Future    125
Dune                    125
Moonfall                125
Avengers: Endgame       124
                       ...
The Tommyknockers         1
Post Impact               1
Red Planet Mars           1
Fate                      1
Clear Skies 2             1
Name: Movie Name, Length: 9572, dtype: int64

In [9]:
df.tail()

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
16144,Suicide Squad,2016,123 min,5.9,"Action, Adventure, Fantasy",A secret government agency recruits some of th...,David Ayer,"(Will Smith, Jared Leto)"
16145,The Hunger Games,2012,142 min,7.2,"Action, Adventure, Sci-Fi",Katniss Everdeen voluntarily takes her younger...,Gary Ross,"(Jennifer Lawrence, Josh Hutcherson)"
16146,Mad Max: Fury Road,2015,120 min,8.1,"Action, Adventure, Sci-Fi","In a post-apocalyptic wasteland, a woman rebel...",George Miller,"(Tom Hardy, Charlize Theron)"
16147,Dune: Part Two,2023,None,None,"Action, Adventure, Drama",The mythic journey continues as Paul Atreides ...,Denis Villeneuve,"(Florence Pugh, Austin Butler)"
16148,Avengers: Infinity War,2018,149 min,8.4,"Action, Adventure, Sci-Fi",The Avengers and their allies must be willing ...,Anthony Russo,"(Joe Russo, Robert Downey Jr.)"

In [10]:
df = df.dropna()
df

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
0,Thor: Love and Thunder,2022,118 min,6.4,"Action, Adventure, Comedy","Thor enlists the help of Valkyrie, Korg and ex...",Taika Waititi,"(Chris Hemsworth, Natalie Portman)"
1,Nope,2022,130 min,7.0,"Horror, Mystery, Sci-Fi",The residents of a lonely gulch in inland Cali...,Jordan Peele,"(Daniel Kaluuya, Keke Palmer)"
3,Everything Everywhere All at Once,2022,139 min,8.1,"Action, Adventure, Comedy",An aging Chinese immigrant is swept up in an i...,Dan Kwan,"(Daniel Scheinert, Michelle Yeoh)"
5,Avatar,2009,162 min,7.8,"Action, Adventure, Fantasy",A paraplegic Marine dispatched to the moon Pan...,James Cameron,"(Sam Worthington, Zoe Saldana)"
6,Jurassic World Dominion,2022,147 min,5.7,"Action, Adventure, Sci-Fi",Four years after the destruction of Isla Nubla...,Colin Trevorrow,"(Chris Pratt, Bryce Dallas Howard)"
...,...,...,...,...,...,...,...,...
16143,A Clockwork Orange,1971,136 min,8.3,"Crime, Sci-Fi","In the future, a sadistic gang leader is impri...",Stanley Kubrick,"(Malcolm McDowell, Patrick Magee)"
16144,Suicide Squad,2016,123 min,5.9,"Action, Adventure, Fantasy",A secret government agency recruits some of th...,David Ayer,"(Will Smith, Jared Leto)"
16145,The Hunger Games,2012,142 min,7.2,"Action, Adventure, Sci-Fi",Katniss Everdeen voluntarily takes her younger...,Gary Ross,"(Jennifer Lawrence, Josh Hutcherson)"
16146,Mad Max: Fury Road,2015,120 min,8.1,"Action, Adventure, Sci-Fi","In a post-apocalyptic wasteland, a woman rebel...",George Miller,"(Tom Hardy, Charlize Theron)"
16148,Avengers: Infinity War,2018,149 min,8.4,"Action, Adventure, Sci-Fi",The Avengers and their allies must be willing ...,Anthony Russo,"(Joe Russo, Robert Downey Jr.)"

In [11]:
df.sort_values("Movie Name", inplace=True)
df

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
8420,'Babicky dobíjejte presne!',1984,101 min,5.7,"Comedy, Horror, Sci-Fi",A family purchases a home robot designed to lo...,Ladislav Rychman,"(Jirí Lábus, Daniela Kolárová)"
5689,(R)Evolutie,2021,83 min,6.5,"Comedy, Drama, Sci-Fi",It's 2040 and most of The Netherlands has been...,Servé Hermans,"(Angela Schijf, Anniek Pheifer)"
2403,(T)Raumschiff Surprise - Periode 1,2004,87 min,5.4,"Comedy, Sci-Fi","Three hundred years in the future, Mars is col...",Michael Herbig,"(Michael Herbig, Rick Kavanian)"
875,*batteries not included,1987,106 min,6.6,"Comedy, Family, Fantasy",Aliens help a feisty old New York couple in th...,Matthew Robbins,"(Hume Cronyn, Jessica Tandy)"
2033,+1,2013,96 min,5.5,"Romance, Sci-Fi, Thriller",Three college friends hit the biggest party of...,Dennis Iliadis,"(Rhys Wakefield, Logan Miller)"
...,...,...,...,...,...,...,...,...
9961,Échenme al gato,1958,90 min,5.7,"Comedy, Crime, Fantasy","In this variation of ""The Hands of Orlac"", the...",Alejandro Galindo,"(Adalberto Martínez, Ariadne Welter)"
6858,Écoute le temps,2006,87 min,5.8,"Crime, Drama, Mystery",The sound engineer Charlotte returns from Pari...,Alante Kavaite,"(Émilie Dequenne, Mathieu Demy)"
6694,Ésimésac,2012,104 min,6.0,"Adventure, Fantasy, Sci-Fi",The residents of Saint-Élie-de-Caxton have bar...,Luc Picard,"(Nicola-Frank Vachon, Gildor Roy)"
1340,Évolution,2015,81 min,5.9,"Drama, Horror, Mystery",The only residents of young Nicholas' sea-side...,Lucile Hadzihalilovic,"(Marta Blanc, Max Brebant)"
1279,Órbita 9,2017,95 min,5.9,"Drama, Romance, Sci-Fi",Helena has lived on a spaceship since birth 20...,Hatem Khraiche,"(Clara Lago, Álex González)"

In [12]:
df['Movie Name'].value_counts()

Prey                              126
Dune                              125
Crimes of the Future              125
Meet Cute                         124
Avengers: Infinity War            124
                                 ...
Guardians of the Galaxy Vol. 2      1
Guardians of the Galaxy             1
Guardians                           1
Guardian of the Realm               1
Órbita 9                            1
Name: Movie Name, Length: 7216, dtype: int64

In [13]:
df = df.drop_duplicates()
df

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
8420,'Babicky dobíjejte presne!',1984,101 min,5.7,"Comedy, Horror, Sci-Fi",A family purchases a home robot designed to lo...,Ladislav Rychman,"(Jirí Lábus, Daniela Kolárová)"
5689,(R)Evolutie,2021,83 min,6.5,"Comedy, Drama, Sci-Fi",It's 2040 and most of The Netherlands has been...,Servé Hermans,"(Angela Schijf, Anniek Pheifer)"
2403,(T)Raumschiff Surprise - Periode 1,2004,87 min,5.4,"Comedy, Sci-Fi","Three hundred years in the future, Mars is col...",Michael Herbig,"(Michael Herbig, Rick Kavanian)"
875,*batteries not included,1987,106 min,6.6,"Comedy, Family, Fantasy",Aliens help a feisty old New York couple in th...,Matthew Robbins,"(Hume Cronyn, Jessica Tandy)"
2033,+1,2013,96 min,5.5,"Romance, Sci-Fi, Thriller",Three college friends hit the biggest party of...,Dennis Iliadis,"(Rhys Wakefield, Logan Miller)"
...,...,...,...,...,...,...,...,...
9961,Échenme al gato,1958,90 min,5.7,"Comedy, Crime, Fantasy","In this variation of ""The Hands of Orlac"", the...",Alejandro Galindo,"(Adalberto Martínez, Ariadne Welter)"
6858,Écoute le temps,2006,87 min,5.8,"Crime, Drama, Mystery",The sound engineer Charlotte returns from Pari...,Alante Kavaite,"(Émilie Dequenne, Mathieu Demy)"
6694,Ésimésac,2012,104 min,6.0,"Adventure, Fantasy, Sci-Fi",The residents of Saint-Élie-de-Caxton have bar...,Luc Picard,"(Nicola-Frank Vachon, Gildor Roy)"
1340,Évolution,2015,81 min,5.9,"Drama, Horror, Mystery",The only residents of young Nicholas' sea-side...,Lucile Hadzihalilovic,"(Marta Blanc, Max Brebant)"
1279,Órbita 9,2017,95 min,5.9,"Drama, Romance, Sci-Fi",Helena has lived on a spaceship since birth 20...,Hatem Khraiche,"(Clara Lago, Álex González)"

In [14]:
df = df.reset_index(drop=True)
df

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
0,'Babicky dobíjejte presne!',1984,101 min,5.7,"Comedy, Horror, Sci-Fi",A family purchases a home robot designed to lo...,Ladislav Rychman,"(Jirí Lábus, Daniela Kolárová)"
1,(R)Evolutie,2021,83 min,6.5,"Comedy, Drama, Sci-Fi",It's 2040 and most of The Netherlands has been...,Servé Hermans,"(Angela Schijf, Anniek Pheifer)"
2,(T)Raumschiff Surprise - Periode 1,2004,87 min,5.4,"Comedy, Sci-Fi","Three hundred years in the future, Mars is col...",Michael Herbig,"(Michael Herbig, Rick Kavanian)"
3,*batteries not included,1987,106 min,6.6,"Comedy, Family, Fantasy",Aliens help a feisty old New York couple in th...,Matthew Robbins,"(Hume Cronyn, Jessica Tandy)"
4,+1,2013,96 min,5.5,"Romance, Sci-Fi, Thriller",Three college friends hit the biggest party of...,Dennis Iliadis,"(Rhys Wakefield, Logan Miller)"
...,...,...,...,...,...,...,...,...
7436,Échenme al gato,1958,90 min,5.7,"Comedy, Crime, Fantasy","In this variation of ""The Hands of Orlac"", the...",Alejandro Galindo,"(Adalberto Martínez, Ariadne Welter)"
7437,Écoute le temps,2006,87 min,5.8,"Crime, Drama, Mystery",The sound engineer Charlotte returns from Pari...,Alante Kavaite,"(Émilie Dequenne, Mathieu Demy)"
7438,Ésimésac,2012,104 min,6.0,"Adventure, Fantasy, Sci-Fi",The residents of Saint-Élie-de-Caxton have bar...,Luc Picard,"(Nicola-Frank Vachon, Gildor Roy)"
7439,Évolution,2015,81 min,5.9,"Drama, Horror, Mystery",The only residents of young Nicholas' sea-side...,Lucile Hadzihalilovic,"(Marta Blanc, Max Brebant)"
7440,Órbita 9,2017,95 min,5.9,"Drama, Romance, Sci-Fi",Helena has lived on a spaceship since birth 20...,Hatem Khraiche,"(Clara Lago, Álex González)"

In [15]:
df

,Movie Name,Year of Release,Watch Time,Movie Rating,Genres,Description,Director,Cast
0,'Babicky dobíjejte presne!',1984,101 min,5.7,"Comedy, Horror, Sci-Fi",A family purchases a home robot designed to lo...,Ladislav Rychman,"(Jirí Lábus, Daniela Kolárová)"
1,(R)Evolutie,2021,83 min,6.5,"Comedy, Drama, Sci-Fi",It's 2040 and most of The Netherlands has been...,Servé Hermans,"(Angela Schijf, Anniek Pheifer)"
2,(T)Raumschiff Surprise - Periode 1,2004,87 min,5.4,"Comedy, Sci-Fi","Three hundred years in the future, Mars is col...",Michael Herbig,"(Michael Herbig, Rick Kavanian)"
3,*batteries not included,1987,106 min,6.6,"Comedy, Family, Fantasy",Aliens help a feisty old New York couple in th...,Matthew Robbins,"(Hume Cronyn, Jessica Tandy)"
4,+1,2013,96 min,5.5,"Romance, Sci-Fi, Thriller",Three college friends hit the biggest party of...,Dennis Iliadis,"(Rhys Wakefield, Logan Miller)"
...,...,...,...,...,...,...,...,...
7436,Échenme al gato,1958,90 min,5.7,"Comedy, Crime, Fantasy","In this variation of ""The Hands of Orlac"", the...",Alejandro Galindo,"(Adalberto Martínez, Ariadne Welter)"
7437,Écoute le temps,2006,87 min,5.8,"Crime, Drama, Mystery",The sound engineer Charlotte returns from Pari...,Alante Kavaite,"(Émilie Dequenne, Mathieu Demy)"
7438,Ésimésac,2012,104 min,6.0,"Adventure, Fantasy, Sci-Fi",The residents of Saint-Élie-de-Caxton have bar...,Luc Picard,"(Nicola-Frank Vachon, Gildor Roy)"
7439,Évolution,2015,81 min,5.9,"Drama, Horror, Mystery",The only residents of young Nicholas' sea-side...,Lucile Hadzihalilovic,"(Marta Blanc, Max Brebant)"
7440,Órbita 9,2017,95 min,5.9,"Drama, Romance, Sci-Fi",Helena has lived on a spaceship since birth 20...,Hatem Khraiche,"(Clara Lago, Álex González)"

In [16]:
df.to_csv('Sci-fi.csv')

In [17]:
df['Genres'].value_counts()

Sci-Fi                                     522
Horror, Sci-Fi                             451
Action, Adventure, Sci-Fi                  319
Comedy, Sci-Fi                             292
Drama, Sci-Fi                              289
                                          ...
Animation, Adventure, Music                  1
Crime, Drama, Fantasy                        1
Comedy, Music, Romance                       1
Action, Fantasy, Romance                     1
Comedy, Sci-Fi, Romance                      1
Name: Genres, Length: 360, dtype: int64